version: 2

workflows:
  version: 2
  simple-workflow:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/

jobs:
  build:
    docker:
      - image: 'fpco/stack-build:latest'

    steps:
      # 'checkout' command is currently broken because the Docker image stopped
      # providing 'ssh'.  We do a manual checkout instead.
      # - checkout
      - run:
          name: 'checkout'
          command: 'git clone https://github.com/jaspervdj/stylish-haskell.git .'
      - restore_cache:
          key: 'v2-stylish-haskell-{{ arch }}-{{ .Branch }}'
      - run:
          name: 'Build, install and test'
          command: 'stack build --test --copy-bins --jobs=1'
      - save_cache:
          key: 'v2-stylish-haskell-{{ arch }}-{{ .Branch }}-{{ .Revision }}'
          paths:
            - '~/.stack-work'
            - '~/.stack'
      - run:
          name: 'Upload release'
          command: '.circleci/release.sh "$CIRCLE_TAG"'
